[[algorithms]]
algo_type = "sniper"
algo_id = "5552"
side = "sell"
quantity = 0.005
price = 89100
base = "sell"
quote = "usdt"

[[algorithms]]
algo_type = "sniper"
algo_id = "343555"
side = "buy"
quantity = 0.5
price = 200
base = "sol"
quote = "usdt"


[[algorithms]]
algo_type = "sniper"
algo_id = "555333"
side = "buy"
quantity = 0.5
price = 3000
base = "buy"
quote = "usdt"
