[[algorithms]]
algo_type = "sniper"
algo_id = "605499"
side = "sell"
quantity = 0.005
price = 92100
base = "btc"
quote = "usdt"

[[algorithms]]
algo_type = "sniper"
algo_id = "786579"
side = "buy"
quantity = 0.5
price = 200
base = "sol"
quote = "usdt"

[[algorithms]]
algo_type = "sniper"
algo_id = "273213"
side = "buy"
quantity = 0.5
price = 3000
base = "eth"
quote = "usdt"
